# Generated by Django 4.1.7 on 2023-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.JSONField(default=dict, verbose_name='Article title'),
        ),
    ]
